CREATE USER pams IDENTIFIED BY pams QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO pams;
GRANT CREATE TABLE TO pams;
GRANT CREATE VIEW TO pams;
GRANT CREATE SEQUENCE TO pams;
GRANT CREATE TRIGGER TO pams;
GRANT CREATE PROCEDURE TO pams;

GRANT UNLIMITED TABLESPACE TO pams;